apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: development
  labels:
    app.kubernetes.io/name: sample-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - development
