---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgAz/FjCvR/FJs+iY7F5cQ2FvFIJuTlvv6InpYvaNb9TYCmksSRJE09M6mik7mJdEW+XL4gCADkEZZNhJNWsIAeQfSXgaYfX5VtFk/+HRT2G/xgUTWyNMv5tMx5TjXazAZp0w6jRSSv2uEw7POSdXPV+c2ebLv2GCooJy8+RTtrdAEHchM4wEkH+tx/z49uZVfhm0RGgjbF1mbv7kiqQlz8Ma6GyVZYJRhOmWZeYRO2SkoZ/jStP5ZdV9rlOJAcJoRgABWyTs/PIxi5dbilLMNhAOqgzSw0c3fltnYjNrqG49f9NlKiMptNybYLY3r30whrnM8S74BdjPb1VW9YjQagU6/9hcE237mzwWe+JGP7WA8Z/jCpbM9Bn9zDw+GlH7vk199KfY4I0TrTwI55Dzc9KKO5VkgFYyGLXIAFjzNG1ewbGRUeSWcG5tHTYat8aExbgUjN3HkXoHe76prBXLi7wlu7ZlTQ7eQCh0AlXHpieiNZ8IAil98Xj/BZd7nCTgOi1/S3pa3QolBWOrczKydbIED5yAndQPn8XzZjaZTpxhYxKm7khd3N+LI8Ve4FG1lJ1POqanIrBse5M4FpbiUPkL2sIIf5H3jn6b4+TuEcNVWCMH3AYsgWx5R7IiV3UBjW/ypMg9x4jITn0HNF8IcAp+Q51ENx5m6VnRd4fH1NOmG5CXyBsESQqFTLgY8Qrm7oMd6KMKWgnkbzj1583gW38uJj9RR/CnI4uIeuR1PVJ5mZBimYFht9WrdUjS9fIavTHrvEsK+F+BzadPM7x0WDqrCnYJMG3b4/HLUr7IhTLIUS4Bx84JWuhQY1brobtdsVmSEQ/elP7nMdlblieNnUQskUwD60rQ6bgmNX1LCASYcurUSue5KYCBLwYa7hpqNvelt50jmUZ3AYJHXPUGvGW7dB/49BIwd+ul2qDJIJV8CPeFA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
