---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgBCXAZ+dP1HPxHCtYSQNEKycpM4J/jlGndT1CEYvKiaglCVIY+wfqExJokbQa6xHELWBPNniJiMrheGjo5JXGopVl3E29CdonxPZ51Xhs8QLCx+FJpLDZkuwQkhGe5wnVCufWrqDjOP0LFpNjGR9EfVJYdJrcFF12nJbLnh8Q9mTy/Fob9KP9fzNveZOKq9de+zYxybvjoYUxkVxcREgoXGdLyJwJX79Z9jWBhAQ7NyhQLRBhN/caiE5gZaNKKNEhXjQG+Jq3AvkzN/OQYuGvTL1lLAZeU19/k4PmEQB7DhVS97LuDUuNbwafsJX/yb1q3dPp6Fb9hi+bV+jKbN5CYqZ09AFTNy18Ld96tBurmXwsr4eY74ohlA5fEP7trGZmbS/3vFGdt296TnywC9/kCYGa8qXcTzqbCviQrtDQwbScU/FxWHglT7Ahe5spzwrdkZvlIo+/bILGSr3/GiG/qGv8AGTaeHGQelyW6eEOmPE7W0PPrWUi/0CwqmPeIG9ofYZb5BhzR/2F2x7V0psITsMc3ffeWQS0IKcemxa8Ru/o6IK5X5eQavpOYXcOWJc3HIzw1qSEcmNUXklXxiD3wn9iSFrkSIDAGySLBPc2mR1BHDqe+99xjaiy8k9fp1h3WpLsVdABBaASWpr4JWf7wVoWptVQMFDNDADqZmFnFAtI0Exrxrr6wc42NL2NqQ3z2jgpnuF+Os4tItECyUwlk8et25yCPvz25UIOSGIRrxdl8NQJUIdDBqd7Zp0Y2DaGHoFxNxQikmlN1u+kVBGCXOnMJMfuPRsz3GI/TKBbucZV2SwqEEFc2eTcPl7Ie1p2y76wg3Kb+Ox010O/uV9GuuTdEOfYIGHkEa37y91igR9Yp5+fZz5JDyCmfqpDzB1Zz2ikdHHno+GYqGaOFtDT+1A/ALRpOmtmaBwcBfiCmR4aWx6w==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
