---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgAM1pXlHjNzMTN3oX044F7ksrIcNvsXGLFmPqpd/m1kYrsSm96gEmLUture6UnghFNaPhZAYi0BePaSPWF5qn7pqbIwuaFXV0quwQsJde2d8uqjLiQ7BUn+DkEXFOHXKLqXArm4a6Cl65cq4HKNMuQ05KN3RtR14nS+mC7cCEkm96o3UDMLdy9+LlJts4AIWSejtFgVBaVAFnhXJMaH3Bi4DQ8Z6sJ78Lk8YhymlTgrOE8ClgLv6qNvSm63oY3P0lehmAf+qq9UlxNjzQrq1pPDzXNcZW+7IyYy5KvSKJn+U7/SCN5s3HwthVZ7VaCavy/4AKzW7qk+pGsset97IBkgmqWMqihQI1IfdYPGZ1SFZ4i2fJLLXMOM9kFz9NbGkWmjqIxHwLqzfgqpobdz2IofZseIYIGkboanYSYREwFRiLK45I/vLEX5D9xWlK/xS6zmIw6VdU9xnVaFS5CXkHgj94Wy37lNGqDU5BEg1rRErKcaCgpuZCBpum/pkVQ4B/GSPnXgEjLrPE1KiBmUgn6dURm6tL8jMtYDHoE/2TcuvdfZ1LXXt07lR4H9LrKpQg4sR6kxVjZFbRRiX28aulJBDlTqoBuFpvuaNuUjTzABU5bjFeag+zX4DwBMCuiw4CR/zi2Yjl1C0AQDQsuzFwoPNxskbKVRyM/Xg4Sx4r63Pkg9Ez+r+d2N5BurdQdcx4KLPkexcb9/G75U1ptsvHUftpBoZkSyIESTdkQ+RyTSaHi9SZJyOqQiTNK/2o8yYGyoJfSn6Pz3A8N2xjKM087TAy7v8EDqhPViykKV300a0hlbfJzCuu/7iuEExXEZYR3r1rJENzW/yHsNvEtT/1iyea5gtkRJEgTIa5e7FODI5chFsG/KITANyl6anMV+22/8XHOK3a4E4NXl+Cd959IobT+euWbfLxNUwR4WIxi41URxEQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
