---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgDixuY7TZsgH1KpLL/Chhb3SUvFg1TuoVOeSly/a0mf0PJMXr+dbG5JJqbQrXmjIpuI9Bzgf9THBLJ6BfVWi8+Alz/rOpoZP702eZqAiqb6vfWtmhQDuJPqYuo13Rp25tiz+GqUKcPe+oPp+ccElmJd3YkOhGYKnowy3TBj6WTQIEY5pjCOB8HgoE4HwTBPRFUCZmyoYL66IkznjFrp8Hxrtir5NdcG931kKS4i3hhFrPvVlVQSeG/zHHx4zA9/r0DsjC6v16ovUOfvEQUHy4Xm3kzcLB23OHcoYPllwxVYk1RA/+lZPNCj+C78aYfx4Lokbhu6wi/Dd539A3uJ+4X/cWgJLVrEeCchsHd66VqWGS2/9/YIjyJ6N5tk/uyaH/cRcnDYi116NxuEA3x2VgUJbojnQjvFVwkF0PsKKJ0s2XUvkc1TMi1o1A8opuxezEJoI9MJkDwYASUy4ezzQwq/8c+JoVOLJ0Sw7YUTclMlsZifWPPHw+hsr3fob1mwCyOw46/hV4Zgq3Nq/T37rnCX3MGt/OSWl23rrMOQpFo5zrRMDpxUf9y5dpKB0VKojoYuRyHDUd3ooeWh5wuJP/yh28ADZLdGoPqomyR0dkOdTD66mRB6uCIyttlkLaQPJICOjAzULGquUX8U9tJlLKdoWMV21+KS/E/PXJaRkk1jSh92TK5587SAs/ODV2r+GxjOxIkh97gWxr3P122xrpmZmLlyPm8i7yXozkZG8YxRVJfGWjGoHnX4X6A2xGqbMwMguUV1lS0P94BySeSrSOT1sP0Cfo7qpOk6g2wFzvKfjM1Lx/ESJ+N3tPArIz17yHNxcRINknSkl9K0ZI/4S6VKl2cEuo2NomYwdfbB2F3Mpzhd/f8adacfI4Y3rEYo1YRTX6iGF57SXTFFXudRtd6vlxhU3io2sqE6BIdZ8JZn8En+eA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
