{{- range .Values.apps }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ .name }}
  namespace: {{ .namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - {{ .namespace }}
              - istio-system
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
{{- end }}
